config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    if user.has_role? :admin  #这里的admin权限等级最高，能增删改查。
      can :manage, :all
    else
      # can :index, :all
      can :read, Article, { user_id: user.id }
      can :update, Article, { user_id: user.id }
 
      can :create, Article
      # can [:read, :edit, :update, :destroy], Article, user_id: user.id
      #can :read, Article, :active => true, :user_id => user.id
      #else之后的用户功能。
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    def self.instance_method_already_implemented?(method_name)
        return true if method_name == 'frozen'
        return true if method_name == 'frozen?'
    end
    

    validates :name, presence: true,
                    length: { minimum: 1 }
    validates :time, presence: true,
                    length: { minimum: 1 }
    validates :content, presence: true,
                    length: { minimum: 1 }
    validates :record, presence: true,
                    length: { minimum: 1 }
    validates :issue, presence: true,
                    length: { minimum: 1 }
    validates :task, presence: true,
                    length: { minimum: 1 }
    validates :summart, presence: true,
                    length: { minimum: 1 }
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles


  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
      def after_sign_in_path_for(resource)
        if resource.is_a?(User)
          if User.count == 1
            resource.add_role 'admin'
          end
          resource
        end
        root_path
      end
  protected
 
  def authenticate_admin
    unless current_user.admin?
      # flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

  def authenticate_client
    unless current_user.client?
      # flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to articles_path, :alert => exception.message
    #return exception.action, exception.subject
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  
  authorize_resource
  
  def index
    @article = Article.all
  end

  # request
  # headers 头部哈希
  # user_id: user_id
  # body 表单参数 json参数
  # url  url 参数

  # request.headers['user_id']

  def new
    @article = Article.new
    puts current_user.id
    @article.user_id = current_user.id
  end

  # body_params = (form_params + json_params)
  # param = url_params + (form_params + json_params)
  # form_params = 

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:name, :time, :content, :record, :issue,
                                    :task, :explain, :summart, :user_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:idcard, :phone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      /ul>
  </div>
<% end %>

<%= form_for(@article) do |f| %>
  <p hidden>
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :日期 %><br>
    <%= f.text_field :time %>
  </p>
  <p>
    <%= f.label :本周完成主要工作内容 %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :本周工作记录，按每日进行说明 %><br>
    <%= f.text_area :record %>
  </p>
  <p>
    <%= f.label :本周工作存在的问题及建议解决方案，是否已经解决 %><br>
    <%= f.text_area :issue %>
  </p>
  <p>
    <%= f.label :下周工作任务 %><br>
    <%= f.text_area :task %>
  </p>
  <p>
    <%= f.label :额外工作说明 %><br>
    <%= f.text_area :explain %>
  </p>
  <p>
    <%= f.label :本周工作总结 %><br>
    <%= f.text_area :summart %>
  </p>
  
  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1 align="center">修改</h1>

<%= render 'form' %>

<h3 align="center"><%= link_to '返回', controller: "articles" %></h3>

app/views/articles/index.html.erb
<h1 align="center">目录</h1>
<h3 align="center"><%= link_to '填写周报', new_article_path %></h3>

<table>
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th colspan="3"></th>
  </tr>
  <% @article.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.time %></td>
      <td><%= link_to '查看', article_path(article) %></td>
      <td><%= link_to '修改', edit_article_path(article) %></td>
      <td><%= link_to '删除', article_path(article),method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    
    </tr>
  <% end %>
</table>
<h3 align="center"><%= link_to '返回首页', controller: 'welcome' %></h3>

app/views/articles/new.html.erb
<h1 align="center">工作周报</h1>

<%= render 'form' %>

<h3 align="center"><%= link_to '返回', controller: "articles" %></h3>

app/views/articles/show.html.erb
<h1>详情</h1>

<p>
  <strong>名字:</strong>
  <%= @article.name %>
</p>
 
<p>
  <strong>时间:</strong>
  <%= @article.time %>
</p>

<p>
  <strong>本周完成主要工作内容:</strong><br>
  <%= @article.content %>
</p>

<p>
  <strong>本周工作记录，按每日进行说明:</strong><br>
  <%= @article.record %>
</p>

<p>
  <strong>本周工作存在的问题及建议解决方案，是否已经解决:</strong><br>
  <%= @article.issue %>
</p>

<p>
  <strong>下周工作任务:</strong><br>
  <%= @article.task %>
</p>

<p>
  <strong>额外工作说明:</strong><br>
  <%= @article.explain %>
</p>

<p>
  <strong>本周工作总结:</strong><br>
  <%= @article.summart %>
</p>

<h3 align="center"><%= link_to '返回目录', controller: 'articles' %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Report</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <div class="col-md-12">
    <%= link_to '首页', root_path %> |
    <% if current_user %>
      Welcome come <%= current_user.email %>
      <%= link_to '退出', destroy_user_session_path, :method => :delete %> |
      <%= link_to '修改密码', edit_registration_path(:user) %>
    <% else %>
      <%= link_to '注册', new_registration_path(:user) %> |
      <%= link_to '登录', new_session_path(:user) %>
    <% end %>
    <p class="text-danger"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idcard %>
    <%= form.text_field :idcard %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Idcard</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.idcard %></td>
        <td><%= list.phone %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
<h3 align="center"><%= link_to 'Home page', controller: "welcome" %></h3>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>
<h3 align="center"><%= link_to 'Home page', controller: "welcome" %></h3>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idcard:</strong>
  <%= @list.idcard %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @list.phone %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/welcome/index.html.erb
<h1 align="center">Welcome everybody</h1>


<h3 align="center"><%= link_to '周报目录', controller: 'articles' %></h3>